set _NUKE_VER_NUM=8.0
set _NUKE_VER_NUM_V=v5
set "NUKE_VERSION=%_NUKE_VER_NUM%%_NUKE_VER_NUM_V%"
set "NUKE_LOCATION=c:\Program Files\Nuke%NUKE_VERSION%"
set "PATH=%MAYA_LOCATION%;%PATH%"
set "DOT_NUKE=%USERPROFILE%\.nuke"
set "NUKEMENUPY"="%DOT_NUKE%\menu.py"
